module.exports = Object.freeze({
    CATEGORY_TYPE_ALL: "ALL",
    CATEGORY_TYPE_CATEGORY: "CATEGORY",
    CATEGORY_TYPE_SUBCATEGORY: "SUBCATEGORY",
    IMAGE_TEMP_UPLOAD_DIR: "temp/",
    IMAGE_THUMB_WIDTH: 200,
    IMAGE_FULL_WIDTH: 600,
    IMAGE_JPEG_QUALITY: 80
});